---
- name: Execute deployment script
  hosts: slave
  user: vagrant
  become: yes

  tasks:
    - name: Copy deployment script
      copy:
        src: ./laravel.sh
        dest: /tmp/laravel.sh
        mode: 0755

    - name: Edit the bash script before execution
      replace:
        path: /tmp/laravel.sh
        regexp: '192.168.56.8'
        replace: '192.168.56.9'
        backup: yes

    - name: Execute deployment script
      shell: /tmp/laravel.sh

    - name: Create a cron job to check the server's uptime every 12 am
      cron:
        name: "check server uptime"
        minute: '0'
        hour: "0"
        job: "uptime >> /vagrant/uptime.log"